<?php
return array(
	'BE' => array(
		'allowDonateWindow' => 0,
		'compressionLevel' => '7',
		'debug' => '1',
		'explicitADmode' => 'explicitAllow',
		'fileCreateMask' => '0664',
		'folderCreateMask' => '2775',
		'installToolPassword' => getenv('TYPO3_INSTALL_TOOL_PASSWORD'),
		'lockSSL' => '2',
		'loginSecurityLevel' => 'rsa',
		'maxFileSize' => 102400,
		'versionNumberInFilename' => 1,
		'warning_email_addr' => 'technik@elemente.ms',
		'warning_mode' => 2,
	),
	'DB' => array(
		'database' => getenv('MYSQL_DATABASE'),
		'extTablesDefinitionScript' => 'extTables.php',
		'host' => getenv('MYSQL_SERVICE_SERVICE_HOST'),
		'password' => getenv('MYSQL_PASSWORD'),
		'port' => getenv('MYSQL_SERVICE_SERVICE_PORT'),
		'socket' => getenv('MYSQL_SERVICE_SERVICE_SOCKET'),
		'username' => getenv('MYSQL_USERNAME'),
	),
	'EXT' => array(
		'extConf' => array(
			'be_secure_pw' => 'a:7:{s:10:"validUntil";s:0:"";s:14:"passwordLength";s:2:"12";s:13:"lowercaseChar";s:1:"1";s:11:"capitalChar";s:1:"1";s:5:"digit";s:1:"1";s:11:"specialChar";s:1:"1";s:8:"patterns";s:1:"3";}',
			'caretaker_instance' => 'a:2:{s:7:"crypto.";a:2:{s:9:"instance.";a:2:{s:9:"publicKey";s:451:"-----BEGIN PUBLIC KEY-----|MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqqRtj90+hDlVGkFSi4T6|U9Ekn/EYckA5e3gTLC5AyYTkrhhGm82rzS12Qi5jtLCrLOk1SpiuzNKkjYzmJxB4|FlAhrXpHlq83oTX8YdTVl/gsStAgtJVCWtzHlCHDkZPjh33qc73Xmwa8MgwffVVd|/NS/38o9rgTyvNIWT2RD92xgM+Ygmd+TM8wgu4cS9XvAIOL2b5tP/qrnFFSE/Uni|yKfynwqE/V1laBGHgvgJOT9xYwh3WdfHVRYxSvbiHWF7BgzJgnYSYLZ6BrX9qtEL|gqrdEeY1lPzdN0oDPRWtgH5QSfFJCNkGTUB9IXgqp2YN3Pae+cnzxuApbDmuSyoc|TwIDAQAB|-----END PUBLIC KEY-----|";s:10:"privateKey";s:1704:"-----BEGIN PRIVATE KEY-----|MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCqpG2P3T6EOVUa|QVKLhPpT0SSf8RhyQDl7eBMsLkDJhOSuGEabzavNLXZCLmO0sKss6TVKmK7M0qSN|jOYnEHgWUCGtekeWrzehNfxh1NWX+CxK0CC0lUJa3MeUIcORk+OHfepzvdebBrwy|DB99VV381L/fyj2uBPK80hZPZEP3bGAz5iCZ35MzzCC7hxL1e8Ag4vZvm0/+qucU|VIT9SeLIp/KfCoT9XWVoEYeC+Ak5P3FjCHdZ18dVFjFK9uIdYXsGDMmCdhJgtnoG|tf2q0QuCqt0R5jWU/N03SgM9Fa2AflBJ8UkI2QZNQH0heCqnZg3c9p75yfPG4Cls|Oa5LKhxPAgMBAAECggEAdsMxrarh08zDOh60gH3wa11oDBkUVo/0ccZEMb+PP7HK|JpCms9EU/Rvi7nSy2BMNT5iPindxUQRZmlqx5AZGTeE/TymHoYwZP43/NWeXsMj8|qqTn3kbzg6GdFa/aGPvAo5AzGJLL+A1b9ckSMXy0iT7Yu7xZ6T9wYZImDONPmmck|H8BChpzfkzums0Ba/JaJVVvW3UYsXMBqh9OmuJmOj1cOUDQ9KZPh/XzrLGubp0XK|T/0psYLrzE4yGIrFibExMg6lWUiW4WJNqtQXwlG7+DFIpWrpYbU1oHcCOrwEpH5x|wf8i/Pbz/3QvpLURCBf1W7WQx74AsjFDA/yjtg4FwQKBgQDVPWzkIKY3MycGl+2p|q4BmtJxgj/doNTW1xXOzhnmbwoAc9FTHNYDplj3dEv2QnN0wBoRFqNNWK5g45RTn|7zNg4YrYJ3Es7Rp4OxULnJq9G/rXI4rhEAY2pd1ONVrMcOM/Q82h5+7fjcvYy8X2|yH3+90q7/BgtoURBQh5/sXSUuQKBgQDM3EWh//OG4cH8FZh6b4hTc6e/sS9Vqhcn|Ecdj59OVFBaPphIjiZQVh1fTmodHUQKhgXjv5bRgjaGhV9LyRnp2K5pN/FArxvAi|I82m4OvwMGsYo7CUlsCBIlZaosI5T1jZHtRaZKLYEZmZnvg80mVpghaXAxbdbTyZ|T+/PVDdFRwKBgA+a2ykmqoNHnweAfsf34QGjHf6DCpv5qOCQfpMYuDWJ2k5EIyAg|7jop4IUZKq02jYlCMNPYMv8PWahwO0Nt4dipKLwAxut+vn0l9bhP0ZMdRRIRa8xk|m8/L+5IJnYdwi3DJyXabvoNloRFQeEBDE9Vgy3tOS4arUo9kA09c8SchAoGAZiTq|X1UEctt74ppN9bZIzftbx9ur01XEx4k41tqPh8SFX0iZwLhnariaFPr2upts6WRq|DYuF/aKA1ba5im2Tv/oLrRjCTKGbuBoL/0okuhUaQSXU9LGZ+IlLb1O57eNfVJrn|nM6S15Mm+A7ojUMGp63iX5d9vhgqX/MYilLeYB8CgYBryX6VigVMJDU3Q7jWbMQm|zwIiHE6cB1Uv2h3tEZgWma3iq0Vrp6OAdRCYxZYSOpQjDTlUHck5BFEo2UmU2eRT|PYL5I1N3eVC71Drt9kTIL6IBendiA32cIL+wlB6ZStvThx1K3o+pkDDzKXwviwBU|labOWsKb1bOHGPor17srcw==|-----END PRIVATE KEY-----|";}s:7:"client.";a:1:{s:9:"publicKey";s:451:"-----BEGIN PUBLIC KEY-----|MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqnrX0fKsifoOLktgn1de|Ll9h9X8MZGSJvAlDSY+Ka+sCIOOlmREFIUd7bu6AnE66Rr6Czf4E9/CKdhKQNTfU|AcDNWIfySfIPAkldJB6Js1QkgKfAMLdJfPGRv6PGWmuC0qMCrqXTqPll90X7e7fk|8q7BCQWKIkgPduVl6MDwjMFdzdv5QoDoYN/FvIt6ZLurA0Ho29WnHuZl9/c2Kbrx|siMD8vwq+5KxQN1D1UZXkyVJqjfeuqGg9ixmwt6gqApHMvMmN5CO8o7LNot+8Ov0|rWMsx7n45i7YSsIjxsiH5ip96TBJqF9SgAhEeXpQOMIZHvIC+SGUF2Je5PkMga5i|3QIDAQAB|-----END PUBLIC KEY-----|";}}s:9:"security.";a:1:{s:28:"clientHostAddressRestriction";s:0:"";}}',
			'direct_mail' => 'a:9:{s:12:"sendPerCycle";s:2:"50";s:13:"cron_language";s:2:"en";s:14:"addRecipFields";s:11:"description";s:10:"adminEmail";s:16:"hinz@elemente.ms";s:7:"cronInt";s:1:"5";s:15:"notificationJob";s:1:"1";s:19:"enablePlainTextNews";s:1:"1";s:14:"UseHttpToFetch";s:1:"0";s:13:"updateMessage";s:1:"0";}',
			'elemente' => 'a:0:{}',
			'indexed_search' => 'a:18:{s:8:"pdftools";s:9:"/usr/bin/";s:8:"pdf_mode";s:2:"20";s:5:"unzip";s:9:"/usr/bin/";s:6:"catdoc";s:9:"/usr/bin/";s:6:"xlhtml";s:9:"/usr/bin/";s:7:"ppthtml";s:9:"/usr/bin/";s:5:"unrtf";s:9:"/usr/bin/";s:9:"debugMode";s:1:"0";s:18:"fullTextDataLength";s:1:"0";s:23:"disableFrontendIndexing";s:1:"0";s:21:"enableMetaphoneSearch";s:1:"1";s:6:"minAge";s:2:"24";s:6:"maxAge";s:1:"0";s:16:"maxExternalFiles";s:1:"5";s:26:"useCrawlerForExternalFiles";s:1:"0";s:11:"flagBitMask";s:3:"192";s:16:"ignoreExtensions";s:0:"";s:17:"indexExternalURLs";s:1:"0";}',
			'indexed_search_mysql' => 'a:0:{}',
			'realurl' => 'a:5:{s:10:"configFile";s:26:"typo3conf/realurl_conf.php";s:14:"enableAutoConf";s:1:"1";s:14:"autoConfFormat";s:1:"0";s:12:"enableDevLog";s:1:"0";s:19:"enableChashUrlDebug";s:1:"0";}',
			'recycler' => 'a:0:{}',
			'rsaauth' => 'a:1:{s:18:"temporaryDirectory";s:0:"";}',
			'rx_shariff' => 'a:4:{s:8:"services";s:77:"GooglePlus,Twitter,Facebook,LinkedIn,Reddit,StumbleUpon,Flattr,Pinterest,Xing";s:3:"ttl";s:2:"60";s:15:"facebook_app_id";s:0:"";s:15:"facebook_secret";s:0:"";}',
			'saltedpasswords' => 'a:2:{s:3:"BE.";a:4:{s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}s:3:"FE.";a:5:{s:7:"enabled";i:1;s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}}',
			'scheduler' => 'a:5:{s:11:"maxLifetime";s:4:"1440";s:11:"enableBELog";s:1:"1";s:15:"showSampleTasks";s:1:"1";s:11:"useAtdaemon";s:1:"0";s:30:"listShowTaskDescriptionAsHover";s:1:"1";}',
			'swmsaboformulare' => 'a:0:{}',
			'sys_action' => 'a:0:{}',
			'taskcenter' => 'a:0:{}',
			'tt_address' => 'a:2:{s:24:"disableCombinedNameField";s:1:"0";s:21:"backwardsCompatFormat";s:9:"%1$s %3$s";}',
		),
	),
	'EXTCONF' => array(
		'lang' => array(
			'availableLanguages' => array(
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'de',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
			),
		),
	),
	'FE' => array(
		'activateContentAdapter' => 0,
		'compressionLevel' => '7',
		'debug' => '1',
		'lifetime' => 0,
		'loginSecurityLevel' => 'rsa',
		'pageNotFound_handling' => '/404.html',
		'secureFormmail' => 1,
		'sessionDataLifetime' => 0,
		'strictFormmail' => 1,
		'versionNumberInFilename' => 'embed',
	),
	'GFX' => array(
		'colorspace' => 'RGB',
		'im' => 1,
		'im_mask_temp_ext_gif' => 1,
		'im_path' => '/usr/bin/',
		'im_path_lzw' => '/usr/bin/',
		'im_v5effects' => -1,
		'im_version_5' => 'gm',
		'image_processing' => 1,
		'jpg_quality' => '80',
	),
	'INSTALL' => array(
		'wizardDone' => array(
			'TYPO3\CMS\Install\Updates\FilemountUpdateWizard' => 1,
			'TYPO3\CMS\Install\Updates\TceformsUpdateWizard' => 'tt_content:image,pages:media,pages_language_overlay:media',
			'TYPO3\CMS\Install\Updates\TruncateSysFileProcessedFileTable' => 1,
		),
	),
	'MAIL' => array(
		'defaultMailFromAddress' => 'info@example.com',
		'defaultMailFromName' => 'Example Applictation',
		'substituteOldMailAPI' => 1,
		'transport' => '',
		'transport_smtp_server' => '',
	),
	'SYS' => array(
		'UTF8filesystem' => '0',
		'caching' => array(
			'cacheConfigurations' => array(
				'extbase_object' => array(
					'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
					'frontend' => 'TYPO3\\CMS\\Core\\Cache\\Frontend\\VariableFrontend',
					'groups' => array(
						'system',
					),
					'options' => array(
						'defaultLifetime' => 0,
					),
				),
			),
		),
		'clearCacheSystem' => '1',
		'compat_version' => '6.2',
		'cookieHttpOnly' => '0',
		'cookieSecure' => '0',
		'dbClientCompress' => '0',
		'ddmmyy' => 'd.m.Y',
		'devIPmask' => '80.153.113.173',
		'displayErrors' => '1',
		'enableDeprecationLog' => '0',
		'enable_DLOG' => '0',
		'encryptionKey' => '59066c0c31a029a4ee469fe4894a27dc984887e30412cf439d1bb5c92378f91cfd3a48877c9fcc2e9ff31af1038caf97',
		'isInitialInstallationInProgress' => FALSE,
		'no_pconnect' => 1,
		'phpTimeZone' => 'Europe/Berlin',
		'serverTimeZone' => 1,
		'sitename' => 'Example TYPO3 Site',
		'sqlDebug' => '0',
		'systemLocale' => '',
		'systemLogLevel' => '2',
		't3lib_cs_convMethod' => 'mbstring',
		't3lib_cs_utils' => 'mbstring',
		'trustedHostsPattern' => '',
		'useCachingFramework' => 1,
	),
);
?>